#ifndef CT_XSLIDER
	#define CT_XSLIDER 43
#endif

#ifndef SL_HORZ
	#define SL_HORZ 0x400
#endif

#ifndef ST_LEFT
	#define ST_LEFT 0
#endif

#ifndef IDC_OK
	#define IDC_OK 1
#endif

#ifndef IDC_CANCEL
	#define IDC_CANCEL 2
#endif

// Common IDCs used by MMB dynamic dialogs.
#define IDC_TITLE 10
#define IDC_BACKGROUND 20
#define IDC_CONTENT 30
#define IDC_BUTTON_EXPORT 40
#define IDC_BUTTON_IMPORT 50

#define IDD_MMB_DYNAMIC_DIALOG 51999
#define IDC_MAIN_GROUP 52000
